# Generated by Django 3.2.7 on 2021-09-30 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'ordering': ['genero'],
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=350, verbose_name='Título')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='books/fotos', verbose_name='Foto capa')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data cadastro')),
                ('ativo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.autor', verbose_name='Autor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genero', verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='CadReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cad_reserva', models.DateField(auto_now_add=True, verbose_name='Data cadastro da reserva')),
                ('ativo', models.BooleanField(default=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.livros', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cadastro Reserva',
                'verbose_name_plural': 'Cadastro Reservas',
                'ordering': ['data_cad_reserva'],
            },
        ),
        migrations.CreateModel(
            name='CadAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cad_aluguel', models.DateField(auto_now_add=True, verbose_name='Data cadastro do aluguel')),
                ('data_renovacao', models.DateField(auto_now=True, verbose_name='Data da renovação')),
                ('ativo', models.BooleanField(default=True)),
                ('devolvido', models.BooleanField(default=False)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.livros', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cadastro Aluguel',
                'verbose_name_plural': 'Cadastro Alugueis',
                'ordering': ['data_cad_aluguel'],
            },
        ),
    ]
