# Generated by Django 3.2.7 on 2021-09-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadaluguel',
            options={'ordering': ['data_cad_aluguel'], 'verbose_name': 'Aluguel', 'verbose_name_plural': 'Alugueis'},
        ),
        migrations.AlterModelOptions(
            name='cadreserva',
            options={'ordering': ['data_cad_reserva'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='livros',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destacar livro?'),
        ),
    ]
