# Generated by Django 3.2.7 on 2021-11-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_livros_alugado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
    ]
