# Generated by Django 3.2.7 on 2021-09-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome: ')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF: ')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone: ')),
                ('rua', models.CharField(max_length=250, verbose_name='Rua: ')),
                ('numero', models.CharField(max_length=6, verbose_name='Número: ')),
                ('bairro', models.CharField(max_length=250, verbose_name='Bairro: ')),
                ('cidade', models.CharField(max_length=250, verbose_name='Cidade: ')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='E-mail: ')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
